#!/bin/bash
# Create input files
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=create_input_files
#SBATCH --output=create_input_files.log
module load R/3.3.1-foss-2016a
Rscript -e 'raket::create_input_files()'
