#!/bin/bash
# Script to install this package and its dependencies
# on the Peregrine computer cluster
#
# Usage, locally:
#
#   ./install_peregrine
#   ./scripts/install_peregrine
#
# Usage, on Peregrine:
#
#   sbatch ./install_peregrine
#   sbatch ./scripts/install_peregrine
#
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=install_peregrine
#SBATCH --output=install_peregrine.log
module load R
Rscript -e 'devtools::install_github("thijsjanzen/nLTT")'
Rscript -e 'devtools::install_github("ropensci/beautier")'
Rscript -e 'devtools::install_github("ropensci/tracerer")'
Rscript -e 'devtools::install_github("ropensci/beastier")'
Rscript -e 'devtools::install_github("ropensci/mauricer")'
Rscript -e 'devtools::install_github("ropensci/babette")'
Rscript -e 'devtools::install_github("richelbilderbeek/mcbette")'
Rscript -e 'devtools::install_github("richelbilderbeek/pirouette")'
Rscript -e 'devtools::install_github("Giappo/mbd")'
Rscript -e 'devtools::install_github("richelbilderbeek/becosys")'
Rscript -e 'devtools::install_github("richelbilderbeek/peregrine", ref = "richel")'
