# This Makefile shows where it is
#
# Usage:
#
# * On Peregrine:
#
#   sbatch run_make.sh
#   ./run_make.sh
#
# * On local:
#
#   ./run_make.sh
#   make
#
#

all:
	echo "HOSTNAME: $HOSTNAME"
	if test -eq $HOSTNAME "peregrine.hpc.rug.nl"; then echo "On Peregrine login node"; fi

